"""empty message

Revision ID: 672ef505c3b6
Revises: 
Create Date: 2017-07-11 19:02:28.632011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672ef505c3b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stations')
    ### end Alembic commands ###
